#!/usr/bin/env python3
"""Cross-platform first-run setup for the FT-991A station console."""

import argparse
import getpass
import hashlib
import os
from pathlib import Path
import secrets
import shutil
import subprocess
import sys


ROOT = Path(__file__).resolve().parent
REQUIREMENTS = ROOT / "requirements.txt"


def platform_profile():
    if os.name == "nt":
        return {
            "name": "Windows",
            "port_hint": "COM7",
            "python_hint": ".venv\\Scripts\\python.exe",
        }
    if sys.platform.startswith("linux"):
        return {
            "name": "Linux",
            "port_hint": "/dev/ttyUSB0",
            "python_hint": ".venv/bin/python",
        }
    return {
        "name": sys.platform,
        "port_hint": "/dev/ttyUSB0",
        "python_hint": ".venv/bin/python",
    }


def run(command, **kwargs):
    print("+", " ".join(str(part) for part in command))
    return subprocess.run(command, cwd=ROOT, check=True, **kwargs)


def venv_python(venv_path):
    path = venv_path / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    if not path.exists():
        raise RuntimeError(f"Virtual-environment Python was not found: {path}")
    return path


def install_dependencies(python_path, force):
    marker = python_path.parent / ".requirements.sha256"
    requirements_hash = hashlib.sha256(REQUIREMENTS.read_bytes()).hexdigest()
    installed_hash = marker.read_text(encoding="utf-8").strip() if marker.exists() else ""
    if installed_hash == requirements_hash and not force:
        print("Dependencies are already up to date.")
        return

    run([str(python_path), "-m", "pip", "install", "--disable-pip-version-check", "-r", str(REQUIREMENTS)])
    marker.write_text(requirements_hash + "\n", encoding="utf-8")


def generate_password_hash(python_path, password):
    code = (
        "from werkzeug.security import generate_password_hash; "
        "import sys; "
        "print(generate_password_hash(sys.stdin.read().rstrip('\\n'), method='scrypt'))"
    )
    result = subprocess.run(
        [str(python_path), "-c", code],
        cwd=ROOT,
        input=password + "\n",
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout.strip()


def ask_password():
    while True:
        password = getpass.getpass("Website password (minimum 5 characters): ")
        if len(password) < 5:
            print("Use at least 5 characters.")
            continue
        confirmation = getpass.getpass("Repeat website password: ")
        if password != confirmation:
            print("Passwords do not match.")
            continue
        return password


def write_config(config_path, secret_key, password_hash, port, baud, profile):
    lines = [
        "# Generated by setup_station.py. Keep this file private.",
        f"# Platform: {profile['name']}",
        f"FT991_PLATFORM={profile['name'].lower()}",
        f"FT991_SECRET_KEY={secret_key}",
        f"FT991_PASSWORD_HASH={password_hash}",
        "FT991_HTTPS=1",
        "FT991_DEBUG=0",
        "FT991_ALLOW_INSECURE_HTTP=0",
        "FT991_HOST=0.0.0.0",
        "FT991_PORT_HTTP=5000",
        f"FT991_PORT={port}",
        f"FT991_BAUD={baud}",
        "FT991_CONFIG=station.env",
    ]
    cert_path = ROOT / "cert.pem"
    key_path = ROOT / "key.pem"
    if cert_path.exists() and key_path.exists():
        lines.extend(["FT991_TLS_CERT=cert.pem", "FT991_TLS_KEY=key.pem"])

    temporary_path = config_path.with_suffix(config_path.suffix + ".tmp")
    temporary_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    if os.name != "nt":
        temporary_path.chmod(0o600)
    temporary_path.replace(config_path)
    if os.name != "nt":
        config_path.chmod(0o600)


def ensure_local_tls_certificate():
    cert_dir = ROOT / "cert"
    cert_path = cert_dir / "localhost.pem"
    key_path = cert_dir / "localhost-key.pem"
    if cert_path.exists() and key_path.exists():
        print(f"Using existing local HTTPS certificate: {cert_path}")
        return True

    for existing_key in sorted(cert_dir.glob("*-key.pem")):
        existing_cert = cert_dir / existing_key.name.replace("-key.pem", ".pem")
        if existing_cert.exists():
            print(f"Using existing local HTTPS certificate: {existing_cert}")
            return True

    openssl = shutil.which("openssl")
    if not openssl:
        print("OpenSSL was not found; the application will use its temporary HTTPS certificate fallback.")
        return False

    cert_dir.mkdir(parents=True, exist_ok=True)
    command = [
        openssl,
        "req",
        "-x509",
        "-nodes",
        "-newkey",
        "rsa:2048",
        "-keyout",
        str(key_path),
        "-out",
        str(cert_path),
        "-days",
        "825",
        "-subj",
        "/CN=localhost",
    ]
    result = subprocess.run(command, cwd=ROOT, check=False, capture_output=True, text=True)
    if result.returncode != 0:
        print("Could not generate a local HTTPS certificate; using the temporary fallback.")
        return False

    if os.name != "nt":
        key_path.chmod(0o600)
    print(f"Generated local HTTPS certificate: {cert_path}")
    return True


def _systemd_quote(path):
    value = str(path).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{value}"'


def _service_contents(python_path, config_path):
    return "\n".join([
        "[Unit]",
        "Description=FT-991A Remote Station Console",
        "Wants=network-online.target",
        "After=network-online.target",
        "",
        "[Service]",
        "Type=simple",
        f"WorkingDirectory={_systemd_quote(ROOT)}",
        f"EnvironmentFile={_systemd_quote(config_path)}",
        f"ExecStart={_systemd_quote(python_path)} {_systemd_quote(ROOT / 'app.py')}",
        "Restart=on-failure",
        "RestartSec=5",
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ])


def install_linux_service(python_path, config_path, start_now):
    if not sys.platform.startswith("linux"):
        return False

    systemctl = shutil.which("systemctl")
    if not systemctl:
        print("Linux detected, but systemctl was not found. Skipping service installation.")
        return False

    service_dir = Path.home() / ".config" / "systemd" / "user"
    service_path = service_dir / "ft991a-remote.service"
    service_dir.mkdir(parents=True, exist_ok=True)
    service_path.write_text(_service_contents(python_path, config_path), encoding="utf-8", newline="\n")

    commands = [
        [systemctl, "--user", "daemon-reload"],
        [systemctl, "--user", "enable", service_path.name],
    ]
    if start_now:
        commands.append([systemctl, "--user", "restart", service_path.name])

    for command in commands:
        result = subprocess.run(command, cwd=ROOT, check=False)
        if result.returncode != 0:
            print(f"Service command failed ({result.returncode}): {' '.join(command)}")
            print(f"Service file was written to {service_path}")
            return False

    loginctl = shutil.which("loginctl")
    if loginctl:
        linger = subprocess.run(
            [loginctl, "enable-linger", getpass.getuser()],
            cwd=ROOT,
            check=False,
        )
        if linger.returncode != 0:
            print("Could not enable user lingering; the service may require a user login before starting.")

    print(f"Linux systemd service enabled: {service_path}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Set up and optionally run the FT-991A remote console.")
    parser.add_argument("--venv", default=".venv", help="Virtual environment directory (default: .venv)")
    parser.add_argument("--force-install", action="store_true", help="Reinstall/update Python dependencies")
    parser.add_argument("--force", action="store_true", help="Replace an existing station.env")
    parser.add_argument("--run", action="store_true", help="Start the application after setup")
    args = parser.parse_args()
    profile = platform_profile()
    print(f"Detected platform: {profile['name']}")

    venv_path = Path(args.venv)
    if not venv_path.is_absolute():
        venv_path = ROOT / venv_path
    config_path = ROOT / "station.env"

    if config_path.exists() and not args.force:
        print(f"{config_path.name} already exists; keeping it unchanged.")
        print("Use --force only when you intend to replace its password and secret.")
        config_exists = True
    else:
        config_exists = False

    if not venv_path.exists():
        run([sys.executable, "-m", "venv", str(venv_path)])
    python_path = venv_python(venv_path)
    install_dependencies(python_path, args.force_install)

    if not config_exists:
        password = ask_password()
        password_hash = generate_password_hash(python_path, password)
        port = input(f"Radio CAT port (optional, e.g. {profile['port_hint']}): ").strip()
        baud = input("CAT baud rate [38400]: ").strip() or "38400"
        if not baud.isdigit():
            raise SystemExit("CAT baud rate must be numeric.")
        write_config(config_path, secrets.token_urlsafe(32), password_hash, port, baud, profile)
        print(f"Wrote private configuration: {config_path}")

    ensure_local_tls_certificate()

    print()
    print("Setup complete.")
    service_enabled = install_linux_service(python_path, config_path, start_now=args.run)
    if service_enabled:
        print("The console will start with Linux user systemd and restart after failures.")
        print("Open the HTTPS URL printed by: systemctl --user status ft991a-remote.service")
    else:
        if profile["name"] == "Windows":
            print("Windows detected: no systemd service was installed.")
        print(f"Start with: {python_path} app.py")
        print("Open the HTTPS URL printed by the application and sign in with your password.")
        if args.run:
            subprocess.run([str(python_path), "app.py"], cwd=ROOT, check=False)


if __name__ == "__main__":
    main()
